services:
  mcphub: # mcp管理中心
    image: registry.cn-hangzhou.aliyuncs.com/jcleng/gitbuild-fast-mcphub-docker
    container_name: mcphub
    network_mode: host
    # http://localhost:3008/mcp/default 需要先创建 default 分组
    environment:
      - ADMIN_PASSWORD=jclengpass
      - PORT=3008
      - PUPPETEER_SKIP_DOWNLOAD=true
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - "/home/jcleng/work/mywork/:/home/jcleng/work/mywork/"
      - ./mcp_settings.json:/app/mcp_settings.json
      # https://github.com/crazywhalecc/static-php-cli
      - "./php:/usr/bin/php"
